# generated by datamodel-codegen:
#   filename:  quality-control-description-json-schema.json
#   timestamp: 2025-02-04T11:54:27+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel
from pydantic import Field


class QualityControlType(Enum):
    H = "H"
    S = "S"
    I = "I"


class Variable(BaseModel):
    variable_description: str | None = None


class JsonSchemaForDescriptionOfQualityControls(BaseModel):
    quality_control_id: str = Field(..., description="A unique quality control ID")
    quality_control_description: str = Field(
        ..., description="Quality control description"
    )
    quality_control_type: QualityControlType = Field(
        ..., description="Quality control type: hard (M), soft (S), informative (I)"
    )
    variables: list[Variable] = Field(
        ...,
        description="A description of which variables must be included in the quality control.",
    )
