name: Labeler

on:
  push:
    branches:
      - main
      - master
    paths:
      - ".github/labels.yml"
      - ".github/workflows/labeler.yml"

jobs:
  labeler:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      contents: read
    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Run Labeler
        uses: crazy-max/ghaction-github-labeler@v5.0.0  # Use this version until https://github.com/crazy-max/ghaction-github-labeler/issues/221 is fixed
        with:
          skip-delete: true
